config/routes.rb
Confident::Application.routes.draw do
  resources :team_games

  resources :games

  resources :team_ratings

  resources :teams

  resources :people do
    collection do
      get :standings
    end
  end

  root :to => 'people#standings'

end

app/models/team_game.rb
class TeamGame < ActiveRecord::Base
  attr_accessible :game, :game_id, :team, :team_id, :score

  belongs_to :team
  belongs_to :game
end

app/controllers/team_games_controller.rb
class TeamGamesController < ApplicationController
  # GET /team_games
  # GET /team_games.json
  def index
    @team_games = TeamGame.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @team_games }
    end
  end

  # GET /team_games/1
  # GET /team_games/1.json
  def show
    @team_game = TeamGame.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team_game }
    end
  end

  # GET /team_games/new
  # GET /team_games/new.json
  def new
    @team_game = TeamGame.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team_game }
    end
  end

  # GET /team_games/1/edit
  def edit
    @team_game = TeamGame.find(params[:id])
  end

  # POST /team_games
  # POST /team_games.json
  def create
    @team_game = TeamGame.new(params[:team_game])

    respond_to do |format|
      if @team_game.save
        format.html { redirect_to @team_game, notice: 'Team game was successfully created.' }
        format.json { render json: @team_game, status: :created, location: @team_game }
      else
        format.html { render action: "new" }
        format.json { render json: @team_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /team_games/1
  # PUT /team_games/1.json
  def update
    @team_game = TeamGame.find(params[:id])

    respond_to do |format|
      if @team_game.update_attributes(params[:team_game])
        format.html { redirect_to @team_game, notice: 'Team game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_games/1
  # DELETE /team_games/1.json
  def destroy
    @team_game = TeamGame.find(params[:id])
    @team_game.destroy

    respond_to do |format|
      format.html { redirect_to team_games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/team_games_helper.rb
module TeamGamesHelper
end

app/views/team_games/_form.html.erb
<%= form_for(@team_game) do |f| %>
  <% if @team_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_game.errors.count, "error") %> prohibited this team_game from being saved:</h2>

      <ul>
      <% @team_game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %><br />
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_games/edit.html.erb
<h1>Editing team_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_game %> |
<%= link_to 'Back', team_games_path %>

app/views/team_games/index.html.erb
<h1>Listing team_games</h1>

<table>
  <tr>
    <th>Team</th>
    <th>Game</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @team_games.each do |team_game| %>
  <tr>
    <td><%= team_game.team %></td>
    <td><%= team_game.game %></td>
    <td><%= team_game.score %></td>
    <td><%= link_to 'Show', team_game %></td>
    <td><%= link_to 'Edit', edit_team_game_path(team_game) %></td>
    <td><%= link_to 'Destroy', team_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Team game', new_team_game_path %>

app/views/team_games/new.html.erb
<h1>New team_game</h1>

<%= render 'form' %>

<%= link_to 'Back', team_games_path %>

app/views/team_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Team:</b>
  <%= @team_game.team %>
</p>

<p>
  <b>Game:</b>
  <%= @team_game.game %>
</p>

<p>
  <b>Score:</b>
  <%= @team_game.score %>
</p>


<%= link_to 'Edit', edit_team_game_path(@team_game) %> |
<%= link_to 'Back', team_games_path %>