config/routes.rb
Confident::Application.routes.draw do
  resources :team_games

  resources :games

  resources :team_ratings

  resources :teams

  resources :people do
    collection do
      get :standings
    end
  end

  root :to => 'people#standings'

end

app/models/team_rating.rb
class TeamRating < ActiveRecord::Base
  attr_accessible :rating, :person, :team, :team_id

  belongs_to :person
  belongs_to :team
end

app/controllers/team_ratings_controller.rb
class TeamRatingsController < ApplicationController
  # GET /team_ratings
  # GET /team_ratings.json
  def index
    @team_ratings = TeamRating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @team_ratings }
    end
  end

  # GET /team_ratings/1
  # GET /team_ratings/1.json
  def show
    @team_rating = TeamRating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team_rating }
    end
  end

  # GET /team_ratings/new
  # GET /team_ratings/new.json
  def new
    @team_rating = TeamRating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team_rating }
    end
  end

  # GET /team_ratings/1/edit
  def edit
    @team_rating = TeamRating.find(params[:id])
  end

  # POST /team_ratings
  # POST /team_ratings.json
  def create
    @team_rating = TeamRating.new(params[:team_rating])

    respond_to do |format|
      if @team_rating.save
        format.html { redirect_to @team_rating, notice: 'Team rating was successfully created.' }
        format.json { render json: @team_rating, status: :created, location: @team_rating }
      else
        format.html { render action: "new" }
        format.json { render json: @team_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /team_ratings/1
  # PUT /team_ratings/1.json
  def update
    @team_rating = TeamRating.find(params[:id])

    respond_to do |format|
      if @team_rating.update_attributes(params[:team_rating])
        format.html { redirect_to @team_rating, notice: 'Team rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_ratings/1
  # DELETE /team_ratings/1.json
  def destroy
    @team_rating = TeamRating.find(params[:id])
    @team_rating.destroy

    respond_to do |format|
      format.html { redirect_to team_ratings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/team_ratings_helper.rb
module TeamRatingsHelper
end

app/views/team_ratings/_form.html.erb
<%= form_for(@team_rating) do |f| %>
  <% if @team_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_rating.errors.count, "error") %> prohibited this team_rating from being saved:</h2>

      <ul>
      <% @team_rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person %><br />
    <%= f.text_field :person %>
  </div>
  <div class="field">
    <%= f.label :team %><br />
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_ratings/edit.html.erb
<h1>Editing team_rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_rating %> |
<%= link_to 'Back', team_ratings_path %>

app/views/team_ratings/index.html.erb
<h1>Listing team_ratings</h1>

<table>
  <tr>
    <th>Person</th>
    <th>Team</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @team_ratings.each do |team_rating| %>
  <tr>
    <td><%= team_rating.person %></td>
    <td><%= team_rating.team %></td>
    <td><%= team_rating.rating %></td>
    <td><%= link_to 'Show', team_rating %></td>
    <td><%= link_to 'Edit', edit_team_rating_path(team_rating) %></td>
    <td><%= link_to 'Destroy', team_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Team rating', new_team_rating_path %>

app/views/team_ratings/new.html.erb
<h1>New team_rating</h1>

<%= render 'form' %>

<%= link_to 'Back', team_ratings_path %>

app/views/team_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @team_rating.person %>
</p>

<p>
  <b>Team:</b>
  <%= @team_rating.team %>
</p>

<p>
  <b>Rating:</b>
  <%= @team_rating.rating %>
</p>


<%= link_to 'Edit', edit_team_rating_path(@team_rating) %> |
<%= link_to 'Back', team_ratings_path %>